/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "resource.h"
/* Header for class taskbar */

#ifndef _Included_taskbar
#define _Included_taskbar
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_net_java_sip_communicator_service_taskbar_TaskbarIconOverlay_SetOverlayIcon
	(JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
